EWPP-1714: Generic webtools service.
openeuropa/oe_webtools pull request #179
Opened 2022-02-11 13:38 UTC by yenyasinn

2022-02-14 08:16 UTC, upchuk requested changes

2022-02-25 11:01 UTC, 22Alexandra requested changes

2022-02-25 11:01 UTC, 22Alexandra commented on modules/oe_webtools_media/tests/src/FunctionalJavascript/MediaSourceWebtoolsTest.php
> +      $assert_session->fieldExists("Webtools {$widget_name} snippet")->setValue('{"service": "' . $invalid_service . '"}');
After adapting the validation messages we should cover both cases of invalid or blacklisted services.

2022-02-28 15:48 UTC, 22Alexandra requested changes
Last changes are not good. We don't need 2 different constraints and all this refactoring. Add 2 different messages in the same constraint and for the validation display the proper message according to the conditions.

2022-03-01 13:39 UTC, 22Alexandra requested changes

2022-03-01 15:32 UTC, 22Alexandra commented on composer.json
> +            "Explicit requirement of phpmd/phpmd due to latest changes in composer",
Please remove this before merging.

2022-03-01 15:32 UTC, 22Alexandra approved these changes

2022-03-09 16:34 UTC, 22Alexandra commented on composer.json
> +        "composer/xdebug-handler": "^2.0",
Please remove this as it has been fixed in code-review: https://github.com/openeuropa/code-review/blob/2.x/composer.json#L7

2022-03-09 17:09 UTC, 22Alexandra submitted a review, later dismissed

2022-03-14 15:38 UTC, imanoleguskiza approved these changes

2022-04-05 08:28 UTC, imanoleguskiza approved these changes

2022-04-05 08:29 UTC, 22Alexandra approved these changes

2022-04-05 08:30 UTC, merged