EWPP-2057: Add Qlik service for chart webtools media.
openeuropa/oe_webtools pull request #183
Opened 2022-03-09 12:17 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-09 16:36 UTC, 22Alexandra requested changes
Changes are good but we need to wait for #179 to be merged as this new service needs to be blacklisted for the Generic service.

2022-04-05 12:13 UTC, 22Alexandra approved these changes

2022-04-06 11:50 UTC, yenyasinn approved these changes

2022-06-13 07:13 UTC, upchuk approved these changes

2022-06-13 07:13 UTC, 22Alexandra approved these changes

2022-06-13 07:13 UTC, merged