EWPP-2709: Make Include field in laco widget settings form as required.
openeuropa/oe_webtools pull request #201
Opened 2022-11-03 14:57 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-11-07 08:17 UTC, upchuk requested changes

2022-11-07 08:17 UTC, upchuk commented on composer.json
> +        "drupal/disable_inline_form_errors": "^1.0"
Why are we adding this module to the require? We don't even enable it

2022-11-08 08:04 UTC, upchuk requested changes

2022-11-10 11:23 UTC, 22Alexandra approved these changes

2022-11-14 13:13 UTC, nagyad approved these changes

2022-11-18 07:55 UTC, upchuk approved these changes

2022-11-18 07:55 UTC, merged