EWPP-3326: Add support of webtools custom dimensions.
openeuropa/oe_webtools pull request #216
Opened 2023-06-16 11:08 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-06-21 10:22 UTC, imanoleguskiza requested changes

2023-06-21 10:22 UTC, imanoleguskiza commented on modules/oe_webtools_analytics/src/AnalyticsEventInterface.php
> +   * Set to true when search with the parameters form SearchParameters class.
This comment doesn't seem correct. Maybe: "Allows to define additional custom dimensions." (taken from the webtools docs)

2023-06-29 08:01 UTC, upchuk approved these changes

2023-06-29 08:03 UTC, 22Alexandra approved these changes
blind

2023-06-29 11:59 UTC, merged