OEL-3178: Add maps version 3.0
openeuropa/oe_webtools pull request #254
Opened 2024-10-11 10:31 UTC by drishu

## OEL-3178

### Description

Add support for maps version 3

### Change log

- Added: Config form
- Changed: field widget

2024-10-25 12:09 UTC, brummbar requested changes
We don't need a new major, we can provide an update path that creates the configuration and sets it to 2.0 for existing installations. New installations can be on 3.0. Sites like EWPP can stick on 2.0 by exporting the configuration.

2024-10-25 12:09 UTC, brummbar commented on modules/oe_webtools_maps/oe_webtools_maps.permissions.yml
> +administer webtools maps form:
This is not in line with the remaining permissions, it should be `administer webtools maps`
https://github.com/openeuropa/oe_webtools/blob/master/modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.permissions.yml#L1
https://github.com/openeuropa/oe_webtools/blob/master/modules/oe_webtools_globan/oe_webtools_globan.permissions.yml#L1
https://github.com/openeuropa/oe_webtools/blob/master/modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.permissions.yml#L1

2024-10-25 12:09 UTC, brummbar commented on modules/oe_webtools_maps/oe_webtools_maps.routing.yml
> +    _title: 'Webtools Maps Form settings'
```suggestion
    _title: 'Webtools Maps settings'
```
Drop the form a bit everywhere :)

2024-10-25 12:09 UTC, brummbar commented on modules/oe_webtools_maps/config/schema/oe_webtools_maps.schema.yml
> +      label: 'Map Version'
```suggestion
      label: 'Map version'
```

2024-12-09 18:01 UTC, piotrsmykaj commented
Hello @drishu,
Here is missing `oe_webtools_maps.links.menu.yml` and the settings form page is not visible on the Admin Configuration page.

2025-01-15 11:32 UTC, drishu commented on modules/oe_webtools_maps/src/Form/WebtoolsMapsSettingsForm.php
> +      '#default_value' => $config->get('map_version') ?? '2.0',
@piotrsmykaj no need for "hook_post_update() and set version 2.0 for the existing websites." as we have this here

2025-01-16 10:57 UTC, sergepavle commented
Unfortunately, somehow, I overlooked this PR regarding the webtools map upgrade and worked on almost the same independently. See PR: https://github.com/openeuropa/oe_webtools/pull/258. 
It doesn't have BC but in my PR implemented some changes regarding webtools Map 3 API changes (missed in this PR).
Here https://github.com/openeuropa/oe_webtools/pull/258/files#diff-d5788593f82f730c0aae0cc4840492e4a812488fa1fb087015bec48283327268L90 you may notice that in new version UAC had a new structure like `layers.markers[0].data` instead of `layers[0].markers` (as worked before). Without that markers
will not be shown.
Maybe you could also extend test coverage by reusing these changes: https://github.com/openeuropa/oe_webtools/pull/258/files#diff-93e9dfce3433d92e9cae1a182d4fb153f8b8169475098c75580da33298e5a187R1 to make sure that formatted settings also was reflected in UAC webtools code.

2025-01-16 11:42 UTC, sergepavle commented on modules/oe_webtools_maps/src/Plugin/Field/FieldFormatter/WebtoolsMapFormatter.php
>            'center' => [
```
if ($this->getSetting('show_marker')) {
        $data_array['layers'] = [
```
should be updated according to changes in Webtools Maps UEC for maps 3.0. See this changes: https://github.com/openeuropa/oe_webtools/pull/258/files#diff-d5788593f82f730c0aae0cc4840492e4a812488fa1fb087015bec48283327268L90

2025-01-16 11:42 UTC, sergepavle commented on modules/oe_webtools_maps/tests/src/Functional/ConfigurationTest.php
> +  public function testConfigurationChanges(): void {
As we didn't have at all test coverage for oe_webtools_maps probably it makes sense to extend test coverage to assert field formatter settings. See https://github.com/openeuropa/oe_webtools/pull/258/files#diff-93e9dfce3433d92e9cae1a182d4fb153f8b8169475098c75580da33298e5a187R71

2025-01-21 09:41 UTC, saidatom commented on modules/oe_webtools_maps/src/Plugin/Field/FieldFormatter/WebtoolsMapFormatter.php
>            'center' => [
I confirm that, without this change, the marker does not appear on the map.

2025-01-27 14:27 UTC, saidatom commented
An additional change following the update to Maps 3.0 is located in the file **tests/Behat/WebtoolsMapsContext.php**
Example:
```
-            if ($map_data->layers[0]->markers->features[0]->properties->name !== $value) {
+            if ($map_data->layers->markers[0]->data->features[0]->properties->name !== $value) {
```

2025-02-20 12:57 UTC, sergepavle approved these changes

2025-03-04 14:51 UTC, merged